# Generated by Django 3.1.1 on 2022-02-24 15:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntregasIncumplidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('order_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor orden de compra')),
                ('days', models.PositiveSmallIntegerField(verbose_name='Días atraso')),
            ],
            options={
                'verbose_name': 'Entrega incumplida',
                'verbose_name_plural': 'Entregas incumplidas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationSuppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('evaluation_type', models.CharField(choices=[('CT', 'Cumplimiento en tiempo de entrega'), ('CP', 'Calidad en productos'), ('PR', 'Precio'), ('FP', 'Forma de pago'), ('FD', 'Flexibilidad de la demanda'), ('DC', 'Documentación')], default='CT', max_length=200, verbose_name='Tipo de evaluación')),
                ('buyer', models.CharField(max_length=200, verbose_name='Comprador')),
                ('general_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Puntaje')),
                ('deliver_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Puntaje cumplimiento entregas')),
                ('quantity_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Puntaje cumplimiento cantidades')),
                ('quality_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Puntaje cumplimiento calidad')),
                ('products_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Puntaje Cumplimiento en productos')),
                ('price_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Puntaje Cumplimiento en precio')),
                ('pay_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Puntaje Cumplimiento en forma de pago')),
                ('demand_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Puntaje Cumplimiento en flexibilidad de la demanda')),
                ('doc_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Puntaje Cumplimiento en documentación')),
                ('obs', models.TextField(verbose_name='Observaciones')),
                ('state', models.CharField(choices=[('AC', 'Activo'), ('IN', 'Inactivo')], default='AC', max_length=200, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Gestión y evaluación proveedor',
                'verbose_name_plural': 'Gestión y evaluación proveedores',
                'ordering': ['id'],
                'permissions': (('bia_pur_sup_eva', 'Evaluación proveedores'),),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='OrderPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('order_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de orden')),
                ('pay_method', models.CharField(choices=[('CR', 'Crédito'), ('CO', 'Contado')], default='CO', max_length=200, verbose_name='Método de pago')),
                ('delivery_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de entrega')),
                ('delivery_address', models.CharField(max_length=200, verbose_name='Dirección de entrega')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('urgency_level', models.CharField(choices=[('AL', 'Alta'), ('MD', 'Media'), ('BJ', 'Baja')], default='AL', max_length=200, verbose_name='Nivel de urgencia')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Iva')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total')),
                ('state', models.CharField(choices=[('AB', 'Abierta'), ('CU', 'Cumplida'), ('CE', 'Cerrada')], default='AB', max_length=200, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Ordenes de compra',
                'ordering': ['id'],
                'permissions': (('bia_pur_order_pur', 'Ordenes de compra'),),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='OrderPurchaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('cant', models.PositiveSmallIntegerField(default=0, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de compra')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Iva')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Detalle orden de compra',
                'verbose_name_plural': 'Detalle ordenes de compra',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='SupplierDebt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('order_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor orden de compra')),
                ('term', models.PositiveSmallIntegerField(verbose_name='Plazo')),
                ('next_payment_date', models.DateField(verbose_name='Fecha de próximo pago orden')),
                ('next_payment_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor próximo pago orden')),
                ('balance_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo pendiente de pago')),
                ('credit_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor crédito')),
                ('balance_credit_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo crédito')),
                ('state', models.CharField(blank=True, choices=[('AC', 'Activa'), ('CE', 'Cerrada'), ('VE', 'Vencida')], default='AC', max_length=200, null=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Cartera proveedor',
                'verbose_name_plural': 'Cartera proveedores',
                'ordering': ['id'],
                'permissions': (('bia_pur_sup_deb', 'Cartera proveedores'),),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='SupplierQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('quote_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de cotización')),
                ('lead_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tiempo entrega')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Iva')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total')),
                ('observations', models.TextField(verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Cotización proveedor',
                'verbose_name_plural': 'Cotizaciones proveedores',
                'ordering': ['id'],
                'permissions': (('bia_pur_quote_pur', 'Cotizaciónes'),),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='SupplierQuoteDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio unitario')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Iva')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio total')),
            ],
            options={
                'verbose_name': 'Detalle cotización',
                'verbose_name_plural': 'Detalle cotizaciones',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='SuppliersPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Pago')),
                ('obs', models.TextField(verbose_name='Observaciones')),
                ('cartera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_compras.supplierdebt', verbose_name='Cartera')),
            ],
            options={
                'verbose_name': 'Pago cliente',
                'verbose_name_plural': 'Pagos clientes',
                'ordering': ['id'],
                'permissions': (('bia_pur_sup_pay', 'Pagos proveedores'),),
                'default_permissions': [],
            },
        ),
    ]
