# Generated by Django 3.1.1 on 2022-03-17 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_configuracion', '0002_auto_20220317_1814'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planeacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseplanning',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planeacion_warehouseplanning_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehouseplanning',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planeacion_warehouseplanning_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseplanning',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planeacion_purchaseplanning_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseplanning',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planeacion_purchaseplanning_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotions',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planeacion_promotions_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotions',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planeacion_promotions_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoproductosmdl', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='promotionproducts',
            name='prom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planeacion.promotions', verbose_name='Código promoción'),
        ),
        migrations.AddField(
            model_name='promotionproducts',
            name='sales_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clsunidadventamdl', verbose_name='Unidad venta'),
        ),
        migrations.AddField(
            model_name='promotionproducts',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planeacion_promotionproducts_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionproducts',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planeacion_promotionproducts_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commercialplanningzone',
            name='customer_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clszonaclientemdl'),
        ),
        migrations.AddField(
            model_name='commercialplanningzone',
            name='planning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planeacion.commercialplanning'),
        ),
        migrations.AddField(
            model_name='commercialplanningzone',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planeacion_commercialplanningzone_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commercialplanningzone',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planeacion_commercialplanningzone_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commercialplanningindicators',
            name='planning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planeacion.commercialplanning'),
        ),
        migrations.AddField(
            model_name='commercialplanningindicators',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planeacion_commercialplanningindicators_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commercialplanningindicators',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planeacion_commercialplanningindicators_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commercialplanningcustomer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoclientesmdl'),
        ),
        migrations.AddField(
            model_name='commercialplanningcustomer',
            name='planning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planeacion.commercialplanning'),
        ),
        migrations.AddField(
            model_name='commercialplanningcustomer',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planeacion_commercialplanningcustomer_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commercialplanningcustomer',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planeacion_commercialplanningcustomer_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commercialplanningclscategoriaclientemdl',
            name='customer_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscategoriaclientemdl'),
        ),
        migrations.AddField(
            model_name='commercialplanningclscategoriaclientemdl',
            name='planning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planeacion.commercialplanning'),
        ),
        migrations.AddField(
            model_name='commercialplanningclscategoriaclientemdl',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planeacion_commercialplanningclscategoriaclientemdl_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commercialplanningclscategoriaclientemdl',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planeacion_commercialplanningclscategoriaclientemdl_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commercialplanningcity',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clsciudadesmdl'),
        ),
        migrations.AddField(
            model_name='commercialplanningcity',
            name='planning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planeacion.commercialplanning'),
        ),
        migrations.AddField(
            model_name='commercialplanningcity',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planeacion_commercialplanningcity_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commercialplanningcity',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planeacion_commercialplanningcity_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commercialplanningadvisor',
            name='commercial_advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clsasesorcomercialmdl'),
        ),
        migrations.AddField(
            model_name='commercialplanningadvisor',
            name='planning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planeacion.commercialplanning'),
        ),
        migrations.AddField(
            model_name='commercialplanningadvisor',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planeacion_commercialplanningadvisor_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commercialplanningadvisor',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planeacion_commercialplanningadvisor_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commercialplanning',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planeacion_commercialplanning_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commercialplanning',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planeacion_commercialplanning_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
