# Generated by Django 3.1.1 on 2022-03-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0003_auto_20220302_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='clsindicadorescomercialesmdl',
            name='indicator_type',
            field=models.CharField(blank=True, choices=[('GN', 'General'), ('DT', 'Detallado')], max_length=200, null=True, verbose_name='Tipo de indicador'),
        ),
        migrations.AlterField(
            model_name='clsindicadorescomercialesmdl',
            name='indicator',
            field=models.CharField(choices=[('VT', 'Venta total'), ('VN', 'Ventas nuevas'), ('PC', 'Profundización clientes'), ('CN', 'Clientes nuevos'), ('MV', 'Margén ventas')], max_length=200, verbose_name='Indicador'),
        ),
    ]
