# Generated by Django 3.1.1 on 2022-03-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0004_auto_20220302_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clsindicadorescomercialesmdl',
            name='indicator_type',
        ),
        migrations.AlterField(
            model_name='clsindicadorescomercialesmdl',
            name='indicator',
            field=models.CharField(max_length=200, verbose_name='Indicador'),
        ),
    ]
