# Generated by Django 3.1.1 on 2022-03-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0005_auto_20220302_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clsindicadorescomercialesmdl',
            name='measurement_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='clsindicadorescomercialesmdl',
            name='objetive',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Objetivo'),
        ),
    ]
