# Generated by Django 3.1.1 on 2022-03-18 09:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('previous_balance', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Saldo anterior')),
                ('inventory_balance', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Saldo de inventario')),
                ('difference', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Diferencia en conteo')),
                ('final_balance', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Saldo final')),
                ('indice_rotacion', models.CharField(max_length=200, verbose_name='Indice de rotación de inventario')),
            ],
            options={
                'verbose_name': 'Inventario de producto',
                'verbose_name_plural': 'Inventario de productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('inventory_type', models.CharField(choices=[('AL', 'Aleatorio'), ('TT', 'Total'), ('SL', 'Selección')], default='AL', max_length=200, verbose_name='Tipo de inventario')),
                ('real_quantity', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Cantidad recibida')),
            ],
            options={
                'verbose_name': 'Conteo de inventario',
                'verbose_name_plural': 'Conteos de inventario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCountDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('first_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Conteo 1')),
                ('second_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Conteo 2')),
                ('third_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Conteo 3')),
                ('difference', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Diferencia')),
            ],
            options={
                'verbose_name': 'Detalle conteo de inventario',
                'verbose_name_plural': 'Detalle conteos de inventario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseOutFlows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('crossing_doc', models.CharField(max_length=200, verbose_name='Documento de cruce')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Iva')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('state', models.CharField(choices=[('CE', 'Cerrada'), ('AN', 'Anulada')], default='CE', max_length=200, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Salida de almacén',
                'verbose_name_plural': 'Salidas de almacén',
                'ordering': ['id'],
                'permissions': (('bia_log_outflows_warehouse', 'Salidas de almacén'),),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='WarehouseOutFlowsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio unitario')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Descuento')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio total')),
                ('batch_record', models.CharField(max_length=200, verbose_name='Lote')),
                ('expiration_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de vencimiento')),
                ('state', models.CharField(choices=[('CE', 'Cerrada'), ('AN', 'Anulada')], default='CE', max_length=200, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Detalle salida de almacén',
                'verbose_name_plural': 'Detalle salidas de almacén',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='WarehouseRevenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('crossing_doc', models.CharField(max_length=200, verbose_name='Documento de cruce')),
                ('documentation', models.BooleanField(default=False, verbose_name='Documentaciòn')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Iva')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('state', models.CharField(choices=[('CA', 'Causada'), ('NC', 'No causada')], default='CA', max_length=200, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Entrada de almacèn',
                'verbose_name_plural': 'Entradas de almacén',
                'ordering': ['id'],
                'permissions': (('bia_log_revenue_warehouse', 'Entradas de almacén'),),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='WarehouseRevenueDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Cantidad recibida')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio unitario')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Descuento')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio total')),
                ('batch_record', models.CharField(max_length=200, verbose_name='Lote')),
                ('expiration_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de vencimiento')),
                ('prod_observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('state', models.CharField(choices=[('CA', 'Causada'), ('NC', 'No causada')], default='CA', max_length=200, verbose_name='Estado')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoproductosmdl')),
            ],
            options={
                'verbose_name': 'Detalle entrada de almacén',
                'verbose_name_plural': 'Detalle entradas de almacén',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
    ]
