# Generated by Django 3.1.1 on 2022-03-17 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_configuracion', '0001_initial'),
        ('modulo_comercial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitsroute',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoclientesmdl', verbose_name='Cliente'),
        ),
    ]
