# Generated by Django 3.1.1 on 2022-03-28 10:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_configuracion', '0002_auto_20220318_0940'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modulo_comercial', '0004_clspromocionesmdl'),
    ]

    operations = [
        migrations.CreateModel(
            name='clsDetallePedidosMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Iva')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total')),
                ('state', models.CharField(choices=[('AB', 'Abierta'), ('CU', 'Cumplida'), ('CE', 'Cerrada')], default='AB', max_length=200, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Detalle pedido',
                'verbose_name_plural': 'Detalle pedidos',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='clsPedidosMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('doc_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Documento Nº')),
                ('order_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de pedido')),
                ('payment_method', models.CharField(choices=[('CR', 'Crédito'), ('CO', 'Contado')], default='CO', max_length=200, verbose_name='Método de pago')),
                ('delivery_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de entrega')),
                ('delivery_address', models.CharField(max_length=200, verbose_name='Dirección de entrega')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Iva')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('state', models.CharField(choices=[('AB', 'Abierta'), ('CU', 'Cumplida'), ('CE', 'Cerrada')], default='AB', max_length=200, verbose_name='Estado')),
                ('identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoclientesmdl')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_comercial_clspedidosmdl_creation', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_comercial_clspedidosmdl_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido cliente',
                'verbose_name_plural': 'Pedidos clientes',
                'ordering': ['id'],
                'permissions': (('bia_com_order', 'Pedidos'),),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='clsVentasPerdidasMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('order_date', models.DateField(verbose_name='Fecha de venta')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Cantidad')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoclientesmdl')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoproductosmdl', verbose_name='Producto')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_comercial_clsventasperdidasmdl_creation', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_comercial_clsventasperdidasmdl_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta perdida',
                'verbose_name_plural': 'Ventas perdidas',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.RemoveField(
            model_name='orders',
            name='identification',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user_update',
        ),
        migrations.RemoveField(
            model_name='ordersdetail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordersdetail',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='ordersdetail',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='ordersdetail',
            name='user_update',
        ),
        migrations.RemoveField(
            model_name='visitsroute',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='visitsroute',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='visitsroute',
            name='user_update',
        ),
        migrations.DeleteModel(
            name='LostSales',
        ),
        migrations.DeleteModel(
            name='OrdersDetail',
        ),
        migrations.DeleteModel(
            name='VisitsRoute',
        ),
        migrations.AddField(
            model_name='clsdetallepedidosmdl',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_comercial.clspedidosmdl', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='clsdetallepedidosmdl',
            name='product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoproductosmdl', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='clsdetallepedidosmdl',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_comercial_clsdetallepedidosmdl_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clsdetallepedidosmdl',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_comercial_clsdetallepedidosmdl_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerdebt',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_comercial.clspedidosmdl', verbose_name='Pedido'),
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
