# Generated by Django 3.1.1 on 2022-03-03 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modulo_configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clsHistoricoMovimientosAlternoMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.CharField(max_length=200, verbose_name='Fecha de creación')),
                ('doc_number', models.CharField(max_length=200, verbose_name='Nº Documento')),
                ('document_type', models.CharField(max_length=200, verbose_name='Tipo de documento')),
                ('type', models.CharField(max_length=200, verbose_name='Tipo de movimiento')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Cantidad')),
                ('batch', models.CharField(max_length=200, verbose_name='Lote')),
                ('expiration_date', models.CharField(max_length=200, verbose_name='Fecha vencimiento')),
                ('unitary_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo unitario')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo total')),
                ('crossing_doc', models.CharField(max_length=200, verbose_name='Documento cruce')),
                ('condition', models.CharField(max_length=200, verbose_name='Condición')),
                ('pre_bal', models.SmallIntegerField(verbose_name='Presaldo')),
                ('balance', models.SmallIntegerField(verbose_name='Saldo')),
                ('inv_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo total')),
                ('identification', models.PositiveBigIntegerField(verbose_name='Identificación')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoproductosmdl')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogobodegasmdl')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historico de movimiento Alterno',
                'verbose_name_plural': 'Historico de movimientos Alterno',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
    ]
