# Generated by Django 3.1.1 on 2022-03-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_configuracion', '0002_clshistoricomovimientosalternomdl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clscatalogoproductosmdl',
            old_name='del_time',
            new_name='supplier_lead_time',
        ),
    ]
