# Generated by Django 3.1.1 on 2022-03-29 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modulo_configuracion', '0002_auto_20220317_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='clsActividadesComercialMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateTimeField(verbose_name='Fecha actividad')),
                ('start_hour', models.CharField(max_length=200, verbose_name='Hora inicio')),
                ('end_hour', models.CharField(max_length=200, verbose_name='Hora fin')),
                ('task', models.CharField(max_length=200, verbose_name='Actividad')),
                ('observation', models.CharField(max_length=200, verbose_name='Actividad')),
                ('condition', models.CharField(choices=[('AC', 'Activo'), ('IN', 'Inactivo')], max_length=200, verbose_name='Condición')),
            ],
            options={
                'verbose_name': 'Actividad comercial',
                'verbose_name_plural': 'Actividades comerciales',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='clsCotizacionesMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('doc_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nº Documento')),
                ('condition', models.CharField(choices=[('AB', 'Abierta'), ('CU', 'Cumplida'), ('CE', 'Cerrada')], max_length=200, verbose_name='Condición')),
                ('freight', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Flete')),
                ('general_obs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones Generales')),
                ('follow_up_date', models.DateTimeField(verbose_name='Fecha de seguimiento')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clsciudadesmdl')),
            ],
            options={
                'verbose_name': 'Cotizaciones',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='clsDetalleClientesPromocionesMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Detalle cliente promoción',
                'verbose_name_plural': 'Detalle clientes promociones',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='clsDetalleCotizacionesMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Cantidad')),
                ('lead_time', models.SmallIntegerField(verbose_name='Tiempo de entrega')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Precio Unitario')),
                ('due_date', models.DateTimeField(verbose_name='Vigencia')),
                ('observations', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('doc_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscotizacionesmdl')),
            ],
            options={
                'verbose_name': 'Detalle cotizaciones',
                'verbose_name_plural': 'Detalle cotizaciones',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='clsDetalleEntradaAlmacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Cantidad')),
                ('unitary_cost', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Costo unitario')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Costo total')),
                ('batch', models.CharField(max_length=200, verbose_name='Lote')),
                ('expiration_date', models.DateTimeField(verbose_name='Fecha vencimiento')),
                ('state', models.CharField(choices=[('CO', 'Completo'), ('IN', 'Incompleto'), ('SU', 'Superior')], max_length=200, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Detalle entrada de almacén',
                'verbose_name_plural': 'Detalle entradas de almacén',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='clsDetalleFiltrosPromocionesMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.CharField(max_length=200, verbose_name='Filtro')),
            ],
            options={
                'verbose_name': 'Detalle filtro promoción',
                'verbose_name_plural': 'Detalle filtros promociones',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='clsDetalleListaPreciosMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Cantidad')),
                ('lead_time', models.SmallIntegerField(verbose_name='Tiempo de entrega')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Precio Unitario')),
                ('due_date', models.DateTimeField(verbose_name='Vigencia')),
                ('observations', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Detalle listas de precios',
                'verbose_name_plural': 'Detalle listas de precios',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='clsDetalleOrdenesCompraMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Detalle ordenes de compra',
                'verbose_name_plural': 'Detalle ordenes de compra',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='clsDetallePedidosMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Detalle pedidos',
                'verbose_name_plural': 'Detalle pedidos',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='clsDetalleProductosPromocionesMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Detalle producto promoción',
                'verbose_name_plural': 'Detalle productos promociones',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='clsEvaluacionProveedorMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Evaluación proveedor',
                'verbose_name_plural': 'Evaluaciones de proveedor',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='clsHistoricoMovimientosAlternoMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.CharField(max_length=200, verbose_name='Fecha de creación')),
                ('doc_number', models.CharField(max_length=200, verbose_name='Nº Documento')),
                ('document_type', models.CharField(max_length=200, verbose_name='Tipo de documento')),
                ('type', models.CharField(max_length=200, verbose_name='Tipo de movimiento')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Cantidad')),
                ('batch', models.CharField(max_length=200, verbose_name='Lote')),
                ('expiration_date', models.CharField(max_length=200, verbose_name='Fecha vencimiento')),
                ('unitary_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo unitario')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo total')),
                ('crossing_doc', models.CharField(max_length=200, verbose_name='Documento cruce')),
                ('condition', models.CharField(max_length=200, verbose_name='Condición')),
                ('pre_bal', models.SmallIntegerField(verbose_name='Presaldo')),
                ('balance', models.SmallIntegerField(verbose_name='Saldo')),
                ('inv_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo total')),
                ('identification', models.PositiveBigIntegerField(verbose_name='Identificación')),
            ],
            options={
                'verbose_name': 'Historico de movimiento Alterno',
                'verbose_name_plural': 'Historico de movimientos Alterno',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='clsIndicadoresAlmacenMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha medición')),
                ('indicator', models.CharField(max_length=200, verbose_name='Indicador')),
                ('objetive', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Objetivo')),
                ('real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Real')),
                ('fulfillment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cumplimiento')),
            ],
            options={
                'verbose_name': 'Indicador almacen',
                'verbose_name_plural': 'Indicadores almacen',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='clsIndicadoresComercialesMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='Fecha creación')),
                ('measurement_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha medición')),
                ('indicator', models.CharField(max_length=200, verbose_name='Indicador')),
                ('set', models.CharField(blank=True, max_length=200, null=True, verbose_name='Conjunto')),
                ('subset', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subconjunto')),
                ('objetive', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Objetivo')),
                ('real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Real')),
                ('fulfillment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cumplimiento')),
            ],
            options={
                'verbose_name': 'Indicador comercial',
                'verbose_name_plural': 'Indicadores comerciales',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='clsIndicadoresComprasMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha medición')),
                ('indicator', models.CharField(max_length=200, verbose_name='Indicador')),
                ('objetive', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Objetivo')),
                ('real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Real')),
                ('fulfillment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cumplimiento')),
            ],
            options={
                'verbose_name': 'Indicador compras',
                'verbose_name_plural': 'Indicadores compras',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='clsListaPreciosMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('doc_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nº Documento')),
                ('list_name', models.CharField(max_length=200, verbose_name='Nombre Lista')),
                ('crossing_doc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Documento Cruce')),
                ('freight', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Flete')),
                ('state', models.CharField(choices=[('AC', 'Activo'), ('IN', 'Inactivo')], max_length=200, verbose_name='Condición')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogobodegasmdl')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_configuracion_clslistapreciosmdl_creation', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_configuracion_clslistapreciosmdl_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listas de precios',
                'verbose_name_plural': 'Lista de precios',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='clsOrdenesCompraMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('doc_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nº Documento')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IVA')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Total')),
                ('observations', models.CharField(max_length=200, verbose_name='Observaciones')),
                ('condition', models.CharField(choices=[('AB', 'Abierta'), ('CU', 'Cumplida'), ('CE', 'Cerrada')], max_length=200, verbose_name='Condición')),
                ('identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoproveedoresmdl')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogobodegasmdl')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_configuracion_clsordenescompramdl_creation', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_configuracion_clsordenescompramdl_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedidos',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='clsPedidosMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('doc_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nº Documento')),
                ('delivery_date', models.DateTimeField(verbose_name='Fecha de entrega')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IVA')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Total')),
                ('observations', models.CharField(max_length=200, verbose_name='Observaciones')),
                ('condition', models.CharField(choices=[('AB', 'Abierta'), ('CU', 'Cumplida'), ('CE', 'Cerrada')], max_length=200, verbose_name='Condición')),
            ],
            options={
                'verbose_name': 'Pedidos',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='clsPromocionesMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(max_length=200, verbose_name='Nº Documento')),
                ('promo_name', models.CharField(max_length=200, verbose_name='Nombre promoción')),
                ('deadline_for_sale', models.DateTimeField(verbose_name='Fecha vigencia')),
                ('promo_quantity', models.SmallIntegerField(verbose_name='Cantidad')),
                ('promo_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Precio promoción')),
                ('promo_object', models.CharField(max_length=200, verbose_name='Objeto promoción')),
                ('auts', models.SmallIntegerField(verbose_name='Unidades autorizadas por cliente')),
                ('condition', models.CharField(choices=[('AC', 'Activo'), ('IN', 'Inactivo')], max_length=200, verbose_name='Condición')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.RemoveField(
            model_name='clshistoricodevolucionesclientemdl',
            name='identification',
        ),
        migrations.RemoveField(
            model_name='clshistoricodevolucionesclientemdl',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='clshistoricodevolucionesclientemdl',
            name='store',
        ),
        migrations.RemoveField(
            model_name='clshistoricodevolucionesproveedormdl',
            name='identification',
        ),
        migrations.RemoveField(
            model_name='clshistoricodevolucionesproveedormdl',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='clshistoricodevolucionesproveedormdl',
            name='store',
        ),
        migrations.RemoveField(
            model_name='clshistoricoentradasalmacenmdl',
            name='identification',
        ),
        migrations.RemoveField(
            model_name='clshistoricoentradasalmacenmdl',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='clshistoricoentradasalmacenmdl',
            name='store',
        ),
        migrations.RemoveField(
            model_name='clshistoricoobsequiosmdl',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='clshistoricoobsequiosmdl',
            name='store',
        ),
        migrations.RemoveField(
            model_name='clshistoricosaldoinicialmdl',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='clshistoricosaldoinicialmdl',
            name='store',
        ),
        migrations.RemoveField(
            model_name='clshistoricosalidasalmacenmdl',
            name='identification',
        ),
        migrations.RemoveField(
            model_name='clshistoricosalidasalmacenmdl',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='clshistoricosalidasalmacenmdl',
            name='store',
        ),
        migrations.RemoveField(
            model_name='clshistoricotrasladosbodegasmdl',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='clshistoricotrasladosbodegasmdl',
            name='store',
        ),
        migrations.RemoveField(
            model_name='clstbldetalleentradaalmacen',
            name='doc_number',
        ),
        migrations.RemoveField(
            model_name='clstbldetalleentradaalmacen',
            name='product_code',
        ),
        migrations.RenameField(
            model_name='clscatalogoproductosmdl',
            old_name='del_time',
            new_name='supplier_lead_time',
        ),
        migrations.RenameField(
            model_name='clscondiciondescuentoproveedormdl',
            old_name='supplier',
            new_name='identification',
        ),
        migrations.RenameField(
            model_name='clscondiciondescuentoproveedormdl',
            old_name='product',
            new_name='product_code',
        ),
        migrations.RenameField(
            model_name='clscondicionminimacompramdl',
            old_name='supplier',
            new_name='identification',
        ),
        migrations.RenameField(
            model_name='clscondicionminimacompramdl',
            old_name='product',
            new_name='product_code',
        ),
        migrations.AlterField(
            model_name='clsajusteinventariomdl',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Total costo'),
        ),
        migrations.AlterField(
            model_name='clsasesorcomercialmdl',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clszonaclientemdl', verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='clscatalogoclientesmdl',
            name='customer_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clszonaclientemdl'),
        ),
        migrations.AlterField(
            model_name='clscatalogoproductosmdl',
            name='product_subcat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clssubcategoriaproductomdl', verbose_name='Subcategoría'),
        ),
        migrations.AlterField(
            model_name='clsdetalleajusteinventariomdl',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total costo'),
        ),
        migrations.AlterField(
            model_name='clsentradasalmacenmdl',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Costo total'),
        ),
        migrations.AlterField(
            model_name='clshistoricomovimientosmdl',
            name='identification',
            field=models.CharField(max_length=200, verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='clshistoricomovimientosmdl',
            name='pre_bal',
            field=models.SmallIntegerField(verbose_name='Presaldo'),
        ),
        migrations.DeleteModel(
            name='clsHistoricoAjustesInventarioMdl',
        ),
        migrations.DeleteModel(
            name='clsHistoricoDevolucionesClienteMdl',
        ),
        migrations.DeleteModel(
            name='clsHistoricoDevolucionesProveedorMdl',
        ),
        migrations.DeleteModel(
            name='clsHistoricoEntradasAlmacenMdl',
        ),
        migrations.DeleteModel(
            name='clsHistoricoObsequiosMdl',
        ),
        migrations.DeleteModel(
            name='clsHistoricoSaldoInicialMdl',
        ),
        migrations.DeleteModel(
            name='clsHistoricoSalidasAlmacenMdl',
        ),
        migrations.DeleteModel(
            name='clsHistoricoTrasladosBodegasMdl',
        ),
        migrations.DeleteModel(
            name='clsTblDetalleEntradaAlmacen',
        ),
        migrations.AddField(
            model_name='clspedidosmdl',
            name='identification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoclientesmdl'),
        ),
        migrations.AddField(
            model_name='clspedidosmdl',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogobodegasmdl'),
        ),
        migrations.AddField(
            model_name='clspedidosmdl',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_configuracion_clspedidosmdl_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clspedidosmdl',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_configuracion_clspedidosmdl_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clshistoricomovimientosalternomdl',
            name='product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoproductosmdl'),
        ),
        migrations.AddField(
            model_name='clshistoricomovimientosalternomdl',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogobodegasmdl'),
        ),
        migrations.AddField(
            model_name='clshistoricomovimientosalternomdl',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clsevaluacionproveedormdl',
            name='incomes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clsentradasalmacenmdl'),
        ),
        migrations.AddField(
            model_name='clsevaluacionproveedormdl',
            name='order_purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clsordenescompramdl'),
        ),
        migrations.AddField(
            model_name='clsdetalleproductospromocionesmdl',
            name='doc_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clspromocionesmdl'),
        ),
        migrations.AddField(
            model_name='clsdetalleproductospromocionesmdl',
            name='product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoproductosmdl'),
        ),
        migrations.AddField(
            model_name='clsdetallepedidosmdl',
            name='doc_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clspedidosmdl'),
        ),
        migrations.AddField(
            model_name='clsdetallepedidosmdl',
            name='product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoproductosmdl'),
        ),
        migrations.AddField(
            model_name='clsdetalleordenescompramdl',
            name='doc_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clsordenescompramdl'),
        ),
        migrations.AddField(
            model_name='clsdetalleordenescompramdl',
            name='product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoproductosmdl'),
        ),
        migrations.AddField(
            model_name='clsdetallelistapreciosmdl',
            name='doc_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clslistapreciosmdl'),
        ),
        migrations.AddField(
            model_name='clsdetallelistapreciosmdl',
            name='product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoproductosmdl'),
        ),
        migrations.AddField(
            model_name='clsdetallefiltrospromocionesmdl',
            name='doc_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clspromocionesmdl'),
        ),
        migrations.AddField(
            model_name='clsdetalleentradaalmacen',
            name='doc_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clsentradasalmacenmdl'),
        ),
        migrations.AddField(
            model_name='clsdetalleentradaalmacen',
            name='product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoproductosmdl'),
        ),
        migrations.AddField(
            model_name='clsdetallecotizacionesmdl',
            name='product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoproductosmdl'),
        ),
        migrations.AddField(
            model_name='clsdetalleclientespromocionesmdl',
            name='doc_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clspromocionesmdl'),
        ),
        migrations.AddField(
            model_name='clsdetalleclientespromocionesmdl',
            name='identification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoclientesmdl'),
        ),
        migrations.AddField(
            model_name='clscotizacionesmdl',
            name='identification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoclientesmdl'),
        ),
        migrations.AddField(
            model_name='clscotizacionesmdl',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogobodegasmdl'),
        ),
        migrations.AddField(
            model_name='clscotizacionesmdl',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_configuracion_clscotizacionesmdl_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clscotizacionesmdl',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_configuracion_clscotizacionesmdl_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clsactividadescomercialmdl',
            name='identification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoclientesmdl'),
        ),
    ]
