# Generated by Django 3.1.1 on 2022-03-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_configuracion', '0003_auto_20220303_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clshistoricomovimientosmdl',
            name='identification',
            field=models.CharField(max_length=200, verbose_name='Identificación'),
        ),
    ]
