# Generated by Django 3.1.1 on 2022-03-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_configuracion', '0003_auto_20220329_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clscatalogoproductosmdl',
            name='quantity_pu',
            field=models.PositiveSmallIntegerField(max_length=5, verbose_name='cantidad por unidad de compra'),
        ),
    ]
