# Generated by Django 3.1.1 on 2022-03-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_configuracion', '0004_auto_20220330_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clscatalogoclientesmdl',
            old_name='credit_value',
            new_name='approved_amount',
        ),
        migrations.AddField(
            model_name='clsordenescompramdl',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='clscatalogoproductosmdl',
            name='quantity_pu',
            field=models.PositiveSmallIntegerField(verbose_name='cantidad por unidad de compra'),
        ),
    ]
