# Generated by Django 3.1.1 on 2022-03-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_configuracion', '0004_auto_20220303_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clssaldosinventariomdl',
            name='product_code',
            field=models.SmallIntegerField(verbose_name='codigo producto'),
        ),
        migrations.AlterField(
            model_name='clssaldosinventariomdl',
            name='store',
            field=models.SmallIntegerField(verbose_name='bodega'),
        ),
    ]
