# Generated by Django 3.1.1 on 2022-03-04 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_configuracion', '0005_auto_20220304_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clssaldosinventariomdl',
            name='product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoproductosmdl'),
        ),
        migrations.AlterField(
            model_name='clssaldosinventariomdl',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogobodegasmdl'),
        ),
    ]
