# Generated by Django 3.1.1 on 2022-03-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_configuracion', '0006_auto_20220304_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clshistoricomovimientosmdl',
            name='identification',
            field=models.SmallIntegerField(verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='clshistoricomovimientosmdl',
            name='product_code',
            field=models.SmallIntegerField(verbose_name='código producto'),
        ),
        migrations.AlterField(
            model_name='clshistoricomovimientosmdl',
            name='store',
            field=models.SmallIntegerField(verbose_name='Bodega'),
        ),
        migrations.AlterField(
            model_name='clssaldosinventariomdl',
            name='product_code',
            field=models.SmallIntegerField(verbose_name='Código producto'),
        ),
        migrations.AlterField(
            model_name='clssaldosinventariomdl',
            name='store',
            field=models.SmallIntegerField(verbose_name='Bodega'),
        ),
    ]
