# Generated by Django 3.1.1 on 2022-03-04 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_configuracion', '0007_auto_20220304_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clshistoricomovimientosmdl',
            name='identification',
            field=models.CharField(max_length=200, verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='clshistoricomovimientosmdl',
            name='product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoproductosmdl'),
        ),
        migrations.AlterField(
            model_name='clshistoricomovimientosmdl',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogobodegasmdl'),
        ),
        migrations.AlterField(
            model_name='clssaldosinventariomdl',
            name='product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoproductosmdl'),
        ),
        migrations.AlterField(
            model_name='clssaldosinventariomdl',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogobodegasmdl'),
        ),
    ]
