# Generated by Django 3.1.1 on 2022-03-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_configuracion', '0008_auto_20220304_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clsajusteinventariomdl',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Total costo'),
        ),
        migrations.AlterField(
            model_name='clsdetalleajusteinventariomdl',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total costo'),
        ),
        migrations.AlterField(
            model_name='clshistoricoajustesinventariomdl',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total costo'),
        ),
        migrations.AlterField(
            model_name='clshistoricomovimientosmdl',
            name='pre_bal',
            field=models.SmallIntegerField(verbose_name='Presaldo'),
        ),
    ]
