# Generated by Django 3.1.1 on 2022-03-09 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modulo_configuracion', '0009_auto_20220307_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='clsOrdenesCompraMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('doc_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nº Documento')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='IVA')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Total')),
                ('observations', models.CharField(max_length=200, verbose_name='Observaciones')),
                ('condition', models.CharField(choices=[('AB', 'Abierta'), ('CU', 'Cumplida'), ('CE', 'Cerrada')], max_length=200, verbose_name='Condición')),
                ('identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoproveedoresmdl')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogobodegasmdl')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_configuracion_clsordenescompramdl_creation', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_configuracion_clsordenescompramdl_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedidos',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='clsPedidosMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('doc_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nº Documento')),
                ('delivery_date', models.DateTimeField(verbose_name='Fecha de entrega')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='IVA')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Total')),
                ('observations', models.CharField(max_length=200, verbose_name='Observaciones')),
                ('condition', models.CharField(choices=[('AB', 'Abierta'), ('CU', 'Cumplida'), ('CE', 'Cerrada')], max_length=200, verbose_name='Condición')),
                ('identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoclientesmdl')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogobodegasmdl')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_configuracion_clspedidosmdl_creation', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_configuracion_clspedidosmdl_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedidos',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='clsTblDetallePedidosMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Total')),
                ('doc_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clspedidosmdl')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoproductosmdl')),
            ],
            options={
                'verbose_name': 'Detalle pedidos',
                'verbose_name_plural': 'Detalle pedidos',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='clsTblDetalleOrdenesCompraMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Total')),
                ('doc_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clsordenescompramdl')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoproductosmdl')),
            ],
            options={
                'verbose_name': 'Detalle ordenes de compra',
                'verbose_name_plural': 'Detalle ordenes de compra',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
    ]
