# Generated by Django 3.1.1 on 2022-03-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_configuracion', '0010_clsordenescompramdl_clspedidosmdl_clstbldetalleordenescompramdl_clstbldetallepedidosmdl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clsTblDetalleOrdenesCompraMdl',
            new_name='clsDetalleOrdenesCompraMdl',
        ),
        migrations.RenameModel(
            old_name='clsTblDetallePedidosMdl',
            new_name='clsDetallePedidosMdl',
        ),
    ]
