# Generated by Django 3.1.1 on 2022-03-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_configuracion', '0012_auto_20220309_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clsentradasalmacenmdl',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Costo total'),
        ),
        migrations.AlterField(
            model_name='clstbldetalleentradaalmacen',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Costo total'),
        ),
        migrations.AlterField(
            model_name='clstbldetalleentradaalmacen',
            name='unitary_cost',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Costo unitario'),
        ),
    ]
