# Generated by Django 3.1.1 on 2022-03-11 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_configuracion', '0013_auto_20220310_1653'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clsTblDetalleEntradaAlmacen',
            new_name='clsDetalleEntradaAlmacen',
        ),
    ]
