# Generated by Django 3.1.1 on 2022-03-14 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modulo_configuracion', '0014_auto_20220311_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='clsCotizacionesMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('doc_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nº Documento')),
                ('condition', models.CharField(choices=[('AB', 'Abierta'), ('CU', 'Cumplida'), ('CE', 'Cerrada')], max_length=200, verbose_name='Condición')),
                ('freight', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Flete')),
                ('general_obs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones Generales')),
                ('follow_up_date', models.DateTimeField(verbose_name='Fecha de seguimiento')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clsciudadesmdl')),
                ('identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoclientesmdl')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogobodegasmdl')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_configuracion_clscotizacionesmdl_creation', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_configuracion_clscotizacionesmdl_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotizaciones',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='clsListaPreciosMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('doc_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nº Documento')),
                ('list_name', models.CharField(max_length=200, verbose_name='Nombre Lista')),
                ('crossing_doc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Documento Cruce')),
                ('freight', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Flete')),
                ('state', models.CharField(choices=[('AC', 'Activo'), ('IN', 'Inactivo')], max_length=200, verbose_name='Condición')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogobodegasmdl')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_configuracion_clslistapreciosmdl_creation', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_configuracion_clslistapreciosmdl_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listas de precios',
                'verbose_name_plural': 'Lista de precios',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='clsDetalleListaPreciosMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Cantidad')),
                ('lead_time', models.SmallIntegerField(verbose_name='Tiempo de entrega')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Precio Unitario')),
                ('due_date', models.DateTimeField(verbose_name='Vigencia')),
                ('observations', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('doc_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clslistapreciosmdl')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoproductosmdl')),
            ],
            options={
                'verbose_name': 'Detalle listas de precios',
                'verbose_name_plural': 'Detalle listas de precios',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='clsDetalleCotizacionesMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Cantidad')),
                ('lead_time', models.SmallIntegerField(verbose_name='Tiempo de entrega')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Precio Unitario')),
                ('due_date', models.DateTimeField(verbose_name='Vigencia')),
                ('observations', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('doc_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscotizacionesmdl')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_configuracion.clscatalogoproductosmdl')),
            ],
            options={
                'verbose_name': 'Detalle cotizaciones',
                'verbose_name_plural': 'Detalle cotizaciones',
                'ordering': ['id'],
                'default_permissions': [],
            },
        ),
    ]
