# Generated by Django 3.1.1 on 2022-03-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_configuracion', '0015_clscotizacionesmdl_clsdetallecotizacionesmdl_clsdetallelistapreciosmdl_clslistapreciosmdl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clscondiciondescuentoproveedormdl',
            old_name='supplier',
            new_name='identification',
        ),
        migrations.RenameField(
            model_name='clscondiciondescuentoproveedormdl',
            old_name='product',
            new_name='product_code',
        ),
        migrations.RenameField(
            model_name='clscondicionminimacompramdl',
            old_name='supplier',
            new_name='identification',
        ),
        migrations.RenameField(
            model_name='clscondicionminimacompramdl',
            old_name='product',
            new_name='product_code',
        ),
    ]
